//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanVeMayBay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class menu
    {
        public int ID { get; set; }
        public string name { get; set; }
        public string type { get; set; }
        public string link { get; set; }
        public Nullable<int> tableid { get; set; }
        public int parentid { get; set; }
        public int orders { get; set; }
        public string position { get; set; }
        public System.DateTime created_at { get; set; }
        public Nullable<int> created_by { get; set; }
        public System.DateTime updated_at { get; set; }
        public Nullable<int> updated_by { get; set; }
        public int status { get; set; }
    
        public virtual user user { get; set; }
    }
}
